### PR TITLE
Use Join-Path cmdlet for dot sourcing

### PR DESCRIPTION
**Pull request by chris-codeflow**
Use **Join-Path** cmdlet instead of **System.IO.Path.Combine** for dot sourcing the **Get-GitHubLatestReleaseLinks.ps1** helper script.

This change keeps the update script more PowerShell native (i.e., without having to use .NET assemblies).

### CODE REVIEW

**Comment by jtcmedia** [comment]
Thanks for your work.

**Comment by chris-codeflow** [comment]
This works with PowerShell 7.x as the Join-Path command has an AdditionalChildPath parameter (that accepts a string array).  Pre PowerShell 7, the Join-Path command did not have the additional parameter.

I tested this locally before creating the PR.

I checked that the *windows-latest* VM image being used in the CI action has PowerShell 7 installed.

**Comment by chris-codeflow** [comment]
I will modify my change to use the older Join-Path (compatible with Windows PowerShell 5.1).

Sorry for any inconvenience caused.

**Comment by chris-codeflow** [comment]
PR #65 submitted to use PowerShell 5.1+ compatible **Join-Path** cmdlet.

**Pull request merged**
